# Generated by Django 5.0.1 on 2024-02-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_stock_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock",
            old_name="close",
            new_name="close_stock",
        ),
        migrations.RenameField(
            model_name="stock",
            old_name="high",
            new_name="high_stock",
        ),
        migrations.RenameField(
            model_name="stock",
            old_name="low",
            new_name="low_stock",
        ),
        migrations.RenameField(
            model_name="stock",
            old_name="open",
            new_name="open_stock",
        ),
    ]
