# Generated by Django 5.0.1 on 2024-02-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_dailystockdata_daily_return_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailystockdata",
            name="daily_close",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="dailystockdata",
            name="daily_high",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="dailystockdata",
            name="daily_low",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="dailystockdata",
            name="daily_open",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="monthlystockdata",
            name="monthly_close",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="monthlystockdata",
            name="monthly_high",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="monthlystockdata",
            name="monthly_low",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="monthlystockdata",
            name="monthly_open",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="yearlystockdata",
            name="yearly_close",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="yearlystockdata",
            name="yearly_high",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="yearlystockdata",
            name="yearly_low",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name="yearlystockdata",
            name="yearly_open",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
