# Generated by Django 5.0.1 on 2024-02-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_dailystockdata_daily_close_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailystockdata",
            name="daily_return",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="monthlystockdata",
            name="monthly_return",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="ticker",
            name="ticker",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="yearlystockdata",
            name="yearly_return",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
