# Generated by Django 5.0.1 on 2024-02-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_dailystockdata_daily_return_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailystockdata",
            name="ticker",
            field=models.CharField(max_length=10),
        ),
        migrations.RemoveField(
            model_name="yearlystockdata",
            name="ticker",
        ),
        migrations.DeleteModel(
            name="MonthlyStockData",
        ),
        migrations.DeleteModel(
            name="Ticker",
        ),
        migrations.DeleteModel(
            name="YearlyStockData",
        ),
    ]
