# Generated by Django 5.0.1 on 2024-03-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_dailystockdata_ticker_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailystockdata",
            name="daily_return",
        ),
    ]
