# Generated by Django 5.0.1 on 2024-03-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_dailystockdata_daily_volume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailystockdata",
            name="daily_volume",
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
    ]
